name: Build and Deploy to GitHub Pages

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          npm install
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
          npm run build

      - name: Deploy 🚀
        if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages/pokesav-trade-web
          FOLDER: dist
          CLEAN: true
