name: Build and Deploy to GitHub Pages

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          npm install
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
          npm run build
